### ISSUE TITLE
Cannot convert the JSON object

### ISSUE THREAD

**Issue by felixtech-msp** [aorfanos/wordpress-exporter#3]
On WordPress 6.2 the exporter only logs "Cannot convert the JSON object" and doesn't export any metrics.
When manually calling the API there is proper JSON outputted, confirming the API and Authentication works.

**Comment by aorfanos** [comment]
hey @felixtech-msp - try https://github.com/aorfanos/wordpress-exporter/pkgs/container/wordpress-exporter%2Fwordpress-exporter and let me know, I spent some time revamping the repo 🚀

**Comment by aorfanos** [comment]
hi @felixtech-msp - does the new version work for your case?

**Comment by aorfanos** [comment]
hi again @felixtech-msp  - I will consider this issue closed, let me know if you continue facing issues
